/*
 * generated by Xtext
 */
package org.eclipse.e4;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CSSRuntimeModule extends org.eclipse.e4.AbstractCSSRuntimeModule {

}
