/*
* generated by Xtext
*/
package org.eclipse.e4.ui.contentassist;

import org.eclipse.e4.ui.contentassist.AbstractCSSProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CSSProposalProvider extends AbstractCSSProposalProvider {

}
