/*
 * generated by Xtext
 */
package org.eclipse.e4.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CSSUiModule extends org.eclipse.e4.ui.AbstractCSSUiModule {
	public CSSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
